# Site settings
title: Hyperlab
email: hi@hyperlab.io
description: > # this means to ignore newlines until "baseurl:"
  Hyperlab Limited
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://hyperlab.io" # the base hostname & protocol for your site
twitter_username: hyperlinkapp
github_username:  hyperlabhq

# Build settings
markdown: kramdown
